# Generated by Django 4.1.3 on 2022-11-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Otify", "0003_region_complaint_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="region",
        ),
        migrations.AddField(
            model_name="complaint",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Otify.region",
            ),
        ),
    ]
